
version: 2

models:
  # - name: my_first_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       tests:
  #         - unique
  #         - not_null

  # - name: my_second_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       tests:
  #         - unique
  #         - not_null
  - name: FIRST_MILESTONE
    description: "Milestone 1"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: SECOND_MILESTONE
    description: "Milestone 2"
  - name: THIRD_MILESTONE
    description: "Milestone 3"
  # - name: FOURTH_MILESTONE
  #   description: "Milestone 4"
  - name: FIFTH_MILESTONE
    description: "Milestone 5"
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     tests:
    #       - unique
    #       - not_null